language: php

php:
    - 7.0
    - 5.6
    - 5.5
    - 5.4

env:
    - SYMFONY_VERSION=3.0.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.6.*

matrix:
    exclude:
        - php: 5.4
          env: SYMFONY_VERSION=3.0.*

    fast_finish: true

before_script:
    - phpenv config-rm xdebug.ini
    - composer selfupdate

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - composer update

script:
    - vendor/bin/atoum
